# Generated by Django 5.2.11 on 2026-02-26 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(default='GBP', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('effective_date', models.DateField()),
                ('source', models.CharField(default='api', max_length=50)),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('supplier', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('debit_card', 'Debit Card')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_local', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('local_currency', models.CharField(blank=True, max_length=3)),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('receipt_ref', models.CharField(blank=True, max_length=100)),
                ('receipt_photo', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('reviewed', 'Reviewed'), ('queried', 'Queried')], default='logged', max_length=20)),
                ('channel', models.CharField(choices=[('app', 'App'), ('whatsapp', 'WhatsApp'), ('web', 'Web'), ('paper', 'Paper')], default='web', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.budgetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.fundingsource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_expenses', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.site')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('project', models.CharField(blank=True, max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_local', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('local_currency', models.CharField(blank=True, max_length=3)),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('debit_card', 'Debit Card')], default='cash', max_length=20)),
                ('receipt_ref', models.CharField(blank=True, max_length=100)),
                ('receipt_photo', models.FileField(blank=True, null=True, upload_to='receipts/projects/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('reviewed', 'Reviewed'), ('queried', 'Queried')], default='logged', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_expenses', to='core.activitytype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expenses', to=settings.AUTH_USER_MODEL)),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expenses', to='core.fundingsource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_expenses', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_expenses', to='core.site')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField()),
                ('annual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.budgetcategory')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.site')),
            ],
            options={
                'ordering': ['site', 'financial_year', 'category'],
                'unique_together': {('site', 'category', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField()),
                ('annual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_budgets', to='core.activitytype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_budgets', to='core.site')),
            ],
            options={
                'unique_together': {('site', 'activity_type', 'financial_year')},
            },
        ),
    ]
