# Generated by Django 5.2.12 on 2026-03-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="channel",
            field=models.CharField(
                choices=[
                    ("app", "App"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("web", "Web"),
                    ("paper", "Paper"),
                ],
                default="web",
                max_length=20,
            ),
        ),
    ]
