# Generated by Django 5.2.12 on 2026-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="budget_warning",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("over_80", "Over 80%"), ("over_100", "Over 100%")],
                default="",
                help_text="Auto-set when expense pushes category budget past 80% or 100%",
                max_length=20,
            ),
        ),
    ]
