# Generated by Django 5.2.12 on 2026-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramIncomingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("update_id", models.BigIntegerField(db_index=True, unique=True)),
                ("chat_id", models.BigIntegerField()),
                ("from_user_id", models.BigIntegerField(blank=True, null=True)),
                ("from_username", models.CharField(blank=True, max_length=100)),
                ("body", models.TextField(blank=True)),
                ("media_file_id", models.CharField(blank=True, max_length=200)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
