# Generated by Django 5.2.12 on 2026-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, help_text="Telegram numeric user ID", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True, help_text="Telegram @username without @", max_length=100
            ),
        ),
    ]
